import { ShieldCheck } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { IssueCertificateForm } from "@/app/(app)/certificates/issue-form";
import { RevokeButton } from "@/app/(app)/certificates/revoke-button";
import { PageHeader } from "@/components/page-header";
import { SecurityClassBadge } from "@/components/security-class-badge";
import { StatusBadge } from "@/components/status-badge";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { can } from "@/lib/auth/rbac";
import { getSession } from "@/lib/auth/session";
import { orchestrator } from "@/lib/crypto/orchestrator";
import { getRootCa } from "@/lib/pki/ca";
import { listCertificates, parseCertificate } from "@/lib/pki/certificates";
import { validateCertificate } from "@/lib/pki/validation";

export const dynamic = "force-dynamic";

export default async function CertificatesPage() {
  const actor = await getSession();
  if (!actor) redirect("/login");

  const ca = await getRootCa().catch(() => null);
  const certificates = await listCertificates(actor);
  const validations = await Promise.all(
    certificates.map(async (certificate) => ({
      id: certificate.id,
      result: await validateCertificate(certificate),
    })),
  );
  const validationById = new Map(validations.map((entry) => [entry.id, entry.result]));
  const canRevoke = can(actor.role, "certificate:revoke");

  return (
    <div className="space-y-6">
      <PageHeader
        icon={ShieldCheck}
        title="Certificates"
        description="Issued by the local root CA. Self-signed and trusted by nothing outside this app."
      />

      <div className="flex flex-wrap items-center gap-x-6 gap-y-2 rounded-xl border bg-card px-5 py-4 shadow-card">
        <div className="flex items-center gap-3">
          <span className="grid h-9 w-9 place-items-center rounded-lg bg-primary/10 text-primary">
            <ShieldCheck aria-hidden className="h-4 w-4" />
          </span>
          <div>
            <div className="text-sm font-medium">Local root Certificate Authority</div>
            <div className="text-xs text-muted-foreground">
              {ca ? `${ca.name} - signing with ${orchestrator.displayName(ca.algorithm)}` : "Not created yet. Run npm run setup."}
            </div>
          </div>
        </div>
        {ca && (
          <div className="text-xs text-muted-foreground sm:ml-auto sm:text-right">
            <div>
              Valid until <span className="font-mono">{parseCertificate(ca.certPem).notAfter.toISOString()}</span>
            </div>
            <div>The CA private key is encrypted at rest with a key stored in a local file, not an HSM or KMS.</div>
          </div>
        )}
      </div>

      {can(actor.role, "certificate:issue") && (
        <Card>
          <CardHeader>
            <CardTitle>Issue a certificate</CardTitle>
            <CardDescription>
              The key pair is generated by the orchestrator for the algorithm you pick; the
              certificate is then signed by the CA.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <IssueCertificateForm algorithms={orchestrator.describeAll()} />
          </CardContent>
        </Card>
      )}

      <Card className="overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Subject</TableHead>
              <TableHead>Algorithm</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Validation</TableHead>
              <TableHead>Expires</TableHead>
              <TableHead>Serial</TableHead>
              {canRevoke && <TableHead />}
            </TableRow>
          </TableHeader>
          <TableBody>
            {certificates.length === 0 && (
              <TableRow>
                <TableCell colSpan={7} className="py-10 text-center text-sm text-muted-foreground">
                  No certificates issued yet.
                </TableCell>
              </TableRow>
            )}
            {certificates.map((certificate) => {
              const validation = validationById.get(certificate.id);
              const metadata = orchestrator.lookup(certificate.algorithm);
              return (
                <TableRow key={certificate.id}>
                  <TableCell>
                    <Link href={`/certificates/${certificate.id}`} className="font-medium hover:underline">
                      {certificate.subject.email}
                    </Link>
                  </TableCell>
                  <TableCell>
                    <div className="flex flex-wrap items-center gap-2">
                      <span>{orchestrator.displayName(certificate.algorithm)}</span>
                      {metadata && <SecurityClassBadge securityClass={metadata.securityClass} />}
                    </div>
                  </TableCell>
                  <TableCell>
                    <StatusBadge status={certificate.status} />
                  </TableCell>
                  <TableCell>
                    {validation?.valid ? (
                      <Badge variant="success">valid</Badge>
                    ) : (
                      <Badge variant="destructive" className="font-mono">
                        {validation?.reason}
                      </Badge>
                    )}
                  </TableCell>
                  <TableCell className="font-mono text-xs text-muted-foreground">
                    {certificate.expiresAt.toISOString().slice(0, 10)}
                  </TableCell>
                  <TableCell className="font-mono text-xs text-muted-foreground" title={certificate.serialNumber}>
                    {certificate.serialNumber.slice(0, 16)}...
                  </TableCell>
                  {canRevoke && (
                    <TableCell className="text-right">
                      {certificate.status !== "REVOKED" && <RevokeButton certificateId={certificate.id} />}
                    </TableCell>
                  )}
                </TableRow>
              );
            })}
          </TableBody>
        </Table>
      </Card>
    </div>
  );
}
