import { redirect } from "next/navigation";
import { IssueCertificateForm } from "@/app/(app)/certificates/issue-form";
import { RevokeButton } from "@/app/(app)/certificates/revoke-button";
import { StatusBadge } from "@/components/status-badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { can } from "@/lib/auth/rbac";
import { getSession } from "@/lib/auth/session";
import { orchestrator } from "@/lib/crypto/orchestrator";
import { getRootCa } from "@/lib/pki/ca";
import { listCertificates, parseCertificate } from "@/lib/pki/certificates";
import { markExpiredCertificates, validateCertificate } from "@/lib/pki/validation";

export const dynamic = "force-dynamic";

export default async function CertificatesPage() {
  const actor = await getSession();
  if (!actor) redirect("/login");

  await markExpiredCertificates();

  const ca = await getRootCa().catch(() => null);
  const certificates = await listCertificates(actor);
  const validations = await Promise.all(
    certificates.map(async (certificate) => ({
      id: certificate.id,
      result: await validateCertificate(certificate),
    })),
  );
  const validationById = new Map(validations.map((entry) => [entry.id, entry.result]));

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Certificates</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Issued by the local root CA. Self-signed and trusted by nothing outside this app.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Local root Certificate Authority</CardTitle>
          <CardDescription>
            {ca
              ? `${ca.name} - signing with ${orchestrator.describe(
                  ca.algorithm as never,
                ).displayName}`
              : "Not created yet. Run npm run setup."}
          </CardDescription>
        </CardHeader>
        {ca && (
          <CardContent className="space-y-1 text-sm text-muted-foreground">
            <div>
              Valid until{" "}
              <span className="font-mono text-xs">
                {parseCertificate(ca.certPem).notAfter.toISOString()}
              </span>
            </div>
            <div>
              The CA private key is encrypted at rest with a key stored in a local file, not an
              HSM or KMS.
            </div>
          </CardContent>
        )}
      </Card>

      {can(actor.role, "certificate:issue") && (
        <Card>
          <CardHeader>
            <CardTitle>Issue a certificate</CardTitle>
            <CardDescription>
              The key pair is generated by the orchestrator for the algorithm you pick; the
              certificate is then signed by the CA.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <IssueCertificateForm algorithms={orchestrator.describeAll()} />
          </CardContent>
        </Card>
      )}

      <div className="rounded-lg border">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Subject</TableHead>
              <TableHead>Algorithm</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Validation</TableHead>
              <TableHead>Expires</TableHead>
              <TableHead>Serial</TableHead>
              {can(actor.role, "certificate:revoke") && <TableHead />}
            </TableRow>
          </TableHeader>
          <TableBody>
            {certificates.length === 0 && (
              <TableRow>
                <TableCell colSpan={7} className="py-8 text-center text-sm text-muted-foreground">
                  No certificates issued yet.
                </TableCell>
              </TableRow>
            )}
            {certificates.map((certificate) => {
              const validation = validationById.get(certificate.id);
              return (
                <TableRow key={certificate.id}>
                  <TableCell>{certificate.subject.email}</TableCell>
                  <TableCell>
                    {orchestrator.describe(certificate.algorithm as never).displayName}
                  </TableCell>
                  <TableCell>
                    <StatusBadge status={certificate.status} />
                  </TableCell>
                  <TableCell className="text-xs">
                    {validation?.valid ? (
                      <span className="text-success">valid</span>
                    ) : (
                      <span className="text-destructive">{validation?.reason}</span>
                    )}
                  </TableCell>
                  <TableCell className="text-xs text-muted-foreground">
                    {certificate.expiresAt.toISOString().slice(0, 10)}
                  </TableCell>
                  <TableCell className="font-mono text-xs text-muted-foreground">
                    {certificate.serialNumber.slice(0, 16)}...
                  </TableCell>
                  {can(actor.role, "certificate:revoke") && (
                    <TableCell>
                      {certificate.status !== "REVOKED" && (
                        <RevokeButton certificateId={certificate.id} />
                      )}
                    </TableCell>
                  )}
                </TableRow>
              );
            })}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}
