// Compares migration-study result files and writes a Markdown report.
//
//   npm run study:compare -- <study.json> <study.json> [...] [--output <report.md>]
//
// Every figure is read from the files; nothing is measured here. The report states each run's
// environment, seed and trust-service algorithms; the precision each run achieved (the 95% confidence
// interval of the mean as a fraction of the mean); sizes along the trust chain side by side; and, for
// every operation, whether pairs of algorithms that differ significantly in one run differ in the
// same direction in the others. Runs on one machine with different seeds show whether findings
// survive a different measurement order; they are not evidence of cross-machine reproducibility.
import fs from "node:fs";
import path from "node:path";
import type { PairwiseComparison } from "../lib/benchmarks/comparison";
import type { SampleSummary } from "../lib/benchmarks/statistics";
import { pairAgreement, relativeHalfWidth } from "../lib/benchmarks/study-comparison";

type SizeRange = { min: number; median: number; max: number };

type Study = {
  schemaVersion: number;
  generatedAt: string;
  durationMs: number;
  environment: { cpu: string; cores: number; node: string; openssl: string; platform: string; gitCommit: string | null; gitTreeDirty: boolean | null };
  parameters: { iterations: number; microIterations: number; warmupRounds?: number; seed?: number };
  isolation: { developmentDatabaseUnchanged: boolean };
  trustServices?: {
    ca: { displayName: string; certificateDerBytes: number };
    tsa: { displayName: string; certificateDerBytes: number };
    emptyCrlDerBytes: number | null;
  };
  algorithms: {
    algorithm: string;
    displayName: string;
    sizes: {
      certificateDerBytes: number;
      signatureBytes: SizeRange;
      cmsSignedDataBytes: SizeRange;
      timestampTokenBytes: SizeRange;
      crlGrowthPerRevokedCertificateBytes: number;
    };
    timings: Record<string, SampleSummary>;
  }[];
  comparisons: Record<string, PairwiseComparison[]>;
  agilityOverhead: { algorithm: string; sign: PairwiseComparison; verify: PairwiseComparison }[];
};

const OPERATION_LABELS: Record<string, string> = {
  certificateIssuance: "Certificate issuance",
  signDocument: "End-to-end signing",
  verifyDocument: "Ten-step verification",
  cmsVerify: "CMS verification",
  orchestratorSign: "Sign primitive (orchestrator)",
  orchestratorVerify: "Verify primitive (orchestrator)",
};

function parseArguments(argv: string[]) {
  const files: string[] = [];
  let output: string | null = null;
  for (let index = 0; index < argv.length; index += 1) {
    if (argv[index] === "--output") output = argv[++index] ?? null;
    else files.push(argv[index]);
  }
  return { files, output };
}

const table = (header: string[], rows: string[][]) =>
  [`| ${header.join(" | ")} |`, `| ${header.map(() => "---").join(" | ")} |`, ...rows.map((cells) => `| ${cells.join(" | ")} |`)].join("\n");

const percent = (value: number | null) => (value === null ? "n/a" : `±${(value * 100).toFixed(1)}%`);

export function compareStudies(runs: { label: string; study: Study }[]): string {
  if (runs.length < 2) throw new Error("Give at least two study files to compare");
  const labels = runs.map((run) => run.label);
  const algorithms = runs[0].study.algorithms.map((entry) => entry.algorithm);
  const nameOf = new Map(runs.flatMap((run) => run.study.algorithms.map((entry) => [entry.algorithm, entry.displayName] as const)));
  const entryOf = (study: Study, algorithm: string) => study.algorithms.find((entry) => entry.algorithm === algorithm);

  const sections: string[] = [];
  sections.push(
    `# Migration study comparison\n\nGenerated by \`npm run study:compare\` on ${new Date().toISOString()} from ${runs.length} result files. ` +
      "Every figure is read from those files. Runs on one machine with different seeds test whether findings survive a different measurement order; they do not establish cross-machine reproducibility.",
  );

  sections.push(
    "## Runs\n\n" +
      table(
        ["Run", "Generated", "Commit", "Machine", "Seed", "n (end-to-end / primitive)", "CA signs with", "TSA signs with", "Development DB unchanged"],
        runs.map(({ label, study }) => [
          label,
          study.generatedAt,
          `${study.environment.gitCommit ?? "unknown"}${study.environment.gitTreeDirty ? " (dirty)" : ""}`,
          `${study.environment.cpu}, Node ${study.environment.node}, OpenSSL ${study.environment.openssl}`,
          String(study.parameters.seed ?? "n/a"),
          `${study.parameters.iterations} / ${study.parameters.microIterations}`,
          study.trustServices?.ca.displayName ?? "not recorded (schema < 3)",
          study.trustServices?.tsa.displayName ?? "not recorded (schema < 3)",
          String(study.isolation.developmentDatabaseUnchanged),
        ]),
      ),
  );

  const sizeRows: string[][] = [
    ["Root CA certificate (DER)", ...runs.map(({ study }) => (study.trustServices ? String(study.trustServices.ca.certificateDerBytes) : "n/a"))],
    ["Time-Stamp Authority certificate (DER)", ...runs.map(({ study }) => (study.trustServices ? String(study.trustServices.tsa.certificateDerBytes) : "n/a"))],
    ["CRL with no entries", ...runs.map(({ study }) => String(study.trustServices?.emptyCrlDerBytes ?? "n/a"))],
  ];
  for (const algorithm of algorithms) {
    const metrics: [string, (entry: Study["algorithms"][number]) => number][] = [
      ["certificate (DER)", (entry) => entry.sizes.certificateDerBytes],
      ["CMS SignedData, median", (entry) => entry.sizes.cmsSignedDataBytes.median],
      ["time-stamp token, median", (entry) => entry.sizes.timestampTokenBytes.median],
      ["CRL growth per revocation", (entry) => entry.sizes.crlGrowthPerRevokedCertificateBytes],
    ];
    for (const [metric, value] of metrics) {
      sizeRows.push([`${nameOf.get(algorithm)}: ${metric}`, ...runs.map(({ study }) => {
        const entry = entryOf(study, algorithm);
        return entry ? String(value(entry)) : "n/a";
      })]);
    }
  }
  sections.push("## Sizes along the trust chain (bytes)\n\n" + table(["Artefact", ...labels], sizeRows));

  const operations = Object.keys(OPERATION_LABELS).filter((operation) => runs.every(({ study }) => study.comparisons[operation]));
  const timingRows: string[][] = [];
  for (const operation of operations) {
    for (const algorithm of algorithms) {
      timingRows.push([
        OPERATION_LABELS[operation],
        nameOf.get(algorithm) ?? algorithm,
        ...runs.map(({ study }) => {
          const summary = entryOf(study, algorithm)?.timings[operation];
          return summary ? `${summary.medianMs.toFixed(3)} (${percent(relativeHalfWidth(summary))}, n=${summary.n})` : "n/a";
        }),
      ]);
    }
  }
  sections.push(
    "## Timings: median milliseconds, with the achieved precision\n\nPrecision is half the 95% confidence interval of the mean, as a percentage of the mean. Absolute timings depend on the machine and the load; compare algorithms within a run.\n\n" +
      table(["Operation", "Algorithm", ...labels], timingRows),
  );

  const agreementRows: string[][] = [];
  const contradictions: string[] = [];
  for (const operation of operations) {
    const pairs = pairAgreement(runs.map(({ study }) => study.comparisons[operation]));
    const count = (agreement: string) => String(pairs.filter((pair) => pair.agreement === agreement).length);
    agreementRows.push([OPERATION_LABELS[operation], String(pairs.length), count("consistent"), count("partly significant"), count("contradictory"), count("never significant")]);
    for (const pair of pairs.filter((candidate) => candidate.agreement === "contradictory")) {
      contradictions.push(`- ${OPERATION_LABELS[operation]}: ${nameOf.get(pair.a)} vs ${nameOf.get(pair.b)} (${pair.directions.join(", ")})`);
    }
  }
  sections.push(
    "## Do significant differences replicate?\n\nFor each pair of algorithms: consistent means significant (Mann-Whitney, Holm-corrected, α = 0.05) in every run in the same direction; partly significant means significant in some runs only; contradictory means significant in opposite directions.\n\n" +
      table(["Operation", "Pairs", "Consistent", "Partly significant", "Contradictory", "Never significant"], agreementRows) +
      (contradictions.length > 0 ? `\n\nContradictory pairs:\n\n${contradictions.join("\n")}` : "\n\nNo pair was significant in opposite directions."),
  );

  sections.push(
    "## Cost of the crypto-agility layer\n\nHodges-Lehmann shift of the orchestrator over a direct provider call, in milliseconds, and whether it is significant.\n\n" +
      table(
        ["Algorithm", ...labels.flatMap((label) => [`${label}: sign`, `${label}: verify`])],
        algorithms.map((algorithm) => [
          nameOf.get(algorithm) ?? algorithm,
          ...runs.flatMap(({ study }) => {
            const row = study.agilityOverhead.find((candidate) => candidate.algorithm === algorithm);
            const cell = (comparison: PairwiseComparison | undefined) =>
              comparison ? `${comparison.hodgesLehmann.toFixed(4)}${comparison.significantAt05 ? " (significant)" : ""}` : "n/a";
            return [cell(row?.sign), cell(row?.verify)];
          }),
        ]),
      ),
  );

  return `${sections.join("\n\n")}\n`;
}

function main() {
  const { files, output } = parseArguments(process.argv.slice(2));
  const runs = files.map((file) => ({ label: path.basename(file, ".json"), study: JSON.parse(fs.readFileSync(file, "utf8")) as Study }));
  const report = compareStudies(runs);
  if (output) {
    fs.mkdirSync(path.dirname(path.resolve(output)), { recursive: true });
    fs.writeFileSync(output, report);
    console.log(`Wrote ${output}`);
  } else {
    process.stdout.write(report);
  }
}

if (process.argv[1]?.endsWith("compare-studies.ts")) main();
