// Runs every Security Lab scenario, each in its own disposable sandbox process, and records the
// results as evidence:
//
//   npm run lab:evaluate
//
// - docs/evidence/security-lab/evaluation.json: every result with its observation, steps, evidence,
//   duration and sandbox clean-up, plus the environment and commit it ran on;
// - docs/threat-model.md: the generated tables between the evaluation markers (adversary
//   capabilities, and scenario -> capability -> mechanism -> expected -> observed outcome).
//
// The application's own database is never opened: runScenarioInSandbox gives each run its own
// database, storage and master key, and the isolation guard refuses anything else.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { ADVERSARIES, SCENARIOS, adversaryFor } from "../lib/security-lab/catalog";
import { runScenarioInSandbox } from "../lib/security-lab/sandbox";

const ROOT = process.cwd();
const OUTPUT = path.join(ROOT, "docs", "evidence", "security-lab", "evaluation.json");
const THREAT_MODEL = path.join(ROOT, "docs", "threat-model.md");
const START = "<!-- evaluation:start (generated by npm run lab:evaluate; do not edit by hand) -->";
const END = "<!-- evaluation:end -->";

function git(args: string[]): string | null {
  try {
    return execFileSync("git", args, { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return null;
  }
}

const cell = (text: string) => text.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");

async function main() {
  const startedAt = new Date();
  const results = [];
  for (const scenario of SCENARIOS) {
    process.stdout.write(`${scenario.id} ... `);
    try {
      const run = await runScenarioInSandbox(scenario.id);
      results.push({
        id: scenario.id,
        title: scenario.title,
        category: scenario.category,
        adversary: scenario.adversary,
        property: scenario.property,
        defence: scenario.defence,
        expected: scenario.expected,
        outcome: run.result.outcome,
        observed: run.result.observed,
        steps: run.result.steps,
        evidence: run.result.evidence,
        durationMs: run.durationMs,
        sandboxRemoved: run.sandboxRemoved,
      });
      console.log(`${run.result.outcome} (${run.durationMs} ms)`);
    } catch (error) {
      // A run that could not complete is recorded as ERROR: it proves nothing either way.
      results.push({
        id: scenario.id,
        title: scenario.title,
        category: scenario.category,
        adversary: scenario.adversary,
        property: scenario.property,
        defence: scenario.defence,
        expected: scenario.expected,
        outcome: "ERROR",
        observed: error instanceof Error ? error.message : String(error),
        steps: [],
        evidence: {},
        durationMs: null,
        sandboxRemoved: null,
      });
      console.log("ERROR");
    }
  }

  const summary = {
    scenarios: results.length,
    held: results.filter((result) => result.outcome === "HELD").length,
    failed: results.filter((result) => result.outcome === "FAILED").length,
    errored: results.filter((result) => result.outcome === "ERROR").length,
  };
  const status = git(["status", "--porcelain"]);
  const report = {
    generatedAt: new Date().toISOString(),
    startedAt: startedAt.toISOString(),
    environment: {
      node: process.version,
      openssl: process.versions.openssl,
      platform: `${os.platform()} ${os.release()}`,
      cpu: os.cpus()[0]?.model?.trim() ?? "unknown",
      gitCommit: git(["rev-parse", "--short", "HEAD"]),
      gitTreeDirty: status === null ? null : status.length > 0,
    },
    method: "Each scenario runs once in a separate process with its own freshly created database, document storage and master key, deleted afterwards. HELD: the control behaved as the catalogue states. FAILED: it did not. ERROR: the scenario could not complete.",
    summary,
    results,
  };
  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, `${JSON.stringify(report, null, 2)}\n`);

  const adversaryTable = [
    "| Capability | In scope | What the adversary can do | Tested by | If not in scope |",
    "| --- | --- | --- | --- | --- |",
    ...ADVERSARIES.map((adversary) => {
      const tested = SCENARIOS.filter((scenario) => scenario.adversary === adversary.id).map((scenario) => `\`${scenario.id}\``);
      return `| \`${adversary.id}\` ${cell(adversary.label)} | ${adversary.inScope ? "yes" : "no"} | ${cell(adversary.capability)} | ${tested.join(", ") || "none"} | ${cell(adversary.consequence ?? "")} |`;
    }),
  ].join("\n");

  const evaluationTable = [
    "| Scenario | Capability | Property | Mechanism relied on | Expected | Outcome | Observed |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...results.map(
      (result) =>
        `| \`${result.id}\` ${cell(result.title)} | ${adversaryFor(result.adversary).label} | ${result.property} | ${cell(result.defence)} | ${cell(result.expected)} | **${result.outcome}** | ${cell(result.observed)} |`,
    ),
  ].join("\n");

  const generated = [
    START,
    "",
    `Last run: ${report.generatedAt}, commit ${report.environment.gitCommit ?? "unknown"}${report.environment.gitTreeDirty ? " with uncommitted changes" : ""}, ${report.environment.cpu}, Node ${report.environment.node}. ` +
      `${summary.held} of ${summary.scenarios} controls held, ${summary.failed} failed, ${summary.errored} errored. Raw results: [\`docs/evidence/security-lab/evaluation.json\`](evidence/security-lab/evaluation.json).`,
    "",
    "### Adversary capabilities",
    "",
    adversaryTable,
    "",
    "### Scenario results",
    "",
    evaluationTable,
    "",
    END,
  ].join("\n");

  const document = fs.readFileSync(THREAT_MODEL, "utf8");
  const start = document.indexOf(START);
  const end = document.indexOf(END);
  if (start === -1 || end === -1 || end < start) throw new Error(`${THREAT_MODEL} is missing its evaluation markers`);
  fs.writeFileSync(THREAT_MODEL, document.slice(0, start) + generated + document.slice(end + END.length));

  console.log(`\n${summary.held}/${summary.scenarios} held, ${summary.failed} failed, ${summary.errored} errored. Wrote ${path.relative(ROOT, OUTPUT)} and updated ${path.relative(ROOT, THREAT_MODEL)}.`);
  if (summary.failed > 0 || summary.errored > 0) process.exitCode = 1;
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
